### ISSUE TITLE
fails to write utf-8 characters

### ISSUE THREAD

**Issue by skyjur** [jessemiller/HamlPy#1]
HamlPy failed to save file with utf-8 characters.

```
Traceback (most recent call last):
  File "/usr/local/bin/hamlpy", line 9, in <module>
    load_entry_point('hamlpy==0.1b1', 'console_scripts', 'hamlpy')()
  File "/usr/local/lib/python2.6/dist-packages/hamlpy-0.1b1-py2.6.egg/hamlpy/hamlpy.py", line 31, in convert_files outFile.write(output)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-1: ordinal not in range(128)
```

**Comment by skyjur** [comment]
I changed line no. 30 and got it working:

```
outfile = codecs.open(sys.argv[2], 'w', encoding='utf-8')
```

**Comment by jessemiller** [comment]
Cool, applied the patch.  Thanks!
