### ISSUE TITLE
Using hamlpy without django

### ISSUE THREAD

**Issue by kylegibson-rldatix** [jessemiller/HamlPy#132]
The latest version of hamlpy now requires django. Seems like an odd thing. Why not create a separate project, django-hamlpy that uses a framework agnostic hamlpy?

```
> pip install -U hamlpy                                                                                                                       (git)-[master]
Downloading/unpacking hamlpy from https://pypi.python.org/packages/source/h/hamlpy/hamlpy-0.82.2.tar.gz#md5=92c911ab6cabda9036f0d9862af6ed21
  Downloading hamlpy-0.82.2.tar.gz
  Running setup.py egg_info for package hamlpy

Downloading/unpacking django (from hamlpy)
  Downloading Django-1.5.1.tar.gz (8.0MB): 143kB downloaded
Operation cancelled by user
```

Let's not download any dependencies:

```
> pip install -U hamlpy --no-deps                                                                                                             (git)-[master] 
Downloading/unpacking hamlpy from https://pypi.python.org/packages/source/h/hamlpy/hamlpy-0.82.2.tar.gz#md5=92c911ab6cabda9036f0d9862af6ed21
  Running setup.py egg_info for package hamlpy

Installing collected packages: hamlpy
  Found existing installation: hamlpy 0.80.4
    Uninstalling hamlpy:
      Successfully uninstalled hamlpy
  Running setup.py install for hamlpy

    Installing hamlpy script to /home/kyle/foobar/bin
    Installing hamlpy-watcher script to /home/kyle/foobar/bin
Successfully installed hamlpy
Cleaning up...
```

Just check the version, right?

```
> hamlpy --version                                                                                                                            (git)-[master] 
Traceback (most recent call last):
  File "/home/kyle/foobar/bin/hamlpy", line 5, in <module>
    from pkg_resources import load_entry_point
  File "build/bdist.linux-i686/egg/pkg_resources.py", line 2603, in <module>
  File "build/bdist.linux-i686/egg/pkg_resources.py", line 666, in require
  File "build/bdist.linux-i686/egg/pkg_resources.py", line 565, in resolve
pkg_resources.DistributionNotFound: django
```

Can't do that.

**Comment by kylegibson-rldatix** [comment]
Looks like this was fixed in #133
