### ISSUE TITLE
commas in tag break

### ISSUE THREAD

**Issue by vbabiy** [jessemiller/HamlPy#74]
This fails in the new version:

```
%meta{name:"viewport", content:"width:device-width, initial-scale:1, minimum-scale:1, maximum-scale:1"}
```

Result:

```
Traceback (most recent call last):
  File "/Users/vbabiy/.virtualenvs/hamlpy/bin/hamlpy", line 8, in <module>
    load_entry_point('hamlpy==0.80.3', 'console_scripts', 'hamlpy')()
  File "/Users/vbabiy/.virtualenvs/hamlpy/lib/python2.7/site-packages/hamlpy/hamlpy.py", line 42, in convert_files
    output = compiler.process_lines(haml_lines)
  File "/Users/vbabiy/.virtualenvs/hamlpy/lib/python2.7/site-packages/hamlpy/hamlpy.py", line 29, in process_lines
    return root.render()
  File "/Users/vbabiy/.virtualenvs/hamlpy/lib/python2.7/site-packages/hamlpy/nodes.py", line 123, in render
    return self.render_internal_nodes()
  File "/Users/vbabiy/.virtualenvs/hamlpy/lib/python2.7/site-packages/hamlpy/nodes.py", line 126, in render_internal_nodes
    return ''.join([node.render() for node in self.internal_nodes])
  File "/Users/vbabiy/.virtualenvs/hamlpy/lib/python2.7/site-packages/hamlpy/nodes.py", line 185, in render
    return self._render_tag()
  File "/Users/vbabiy/.virtualenvs/hamlpy/lib/python2.7/site-packages/hamlpy/nodes.py", line 188, in _render_tag
    self.element = Element(self.haml)
  File "/Users/vbabiy/.virtualenvs/hamlpy/lib/python2.7/site-packages/hamlpy/elements.py", line 36, in __init__
    self._parse_haml()
  File "/Users/vbabiy/.virtualenvs/hamlpy/lib/python2.7/site-packages/hamlpy/elements.py", line 41, in _parse_haml
    self.attributes_dict = self._parse_attribute_dictionary(split_tags.get('attributes'))
  File "/Users/vbabiy/.virtualenvs/hamlpy/lib/python2.7/site-packages/hamlpy/elements.py", line 123, in _parse_attribute_dictionary
    raise Exception('failed to decode: %s'%attribute_dict_string)
Exception: failed to decode: {"name":"viewport", "content":"width:device-width, "initial-scale":1, "minimum-scale":1, "maximum-scale":1"}
```

**Comment by bcoughlan** [comment]
Working on a fix now.

Details: My fix for #72 caused this bug to show up in your particular case, but isn't the direct cause. The regex in _parse_attributes_dictionary (elements.py) which puts quotes around the attribute keys isn't discriminating between keys and values correctly, causing this:

   {style:"a:1, b:'y', c:1"}

to compile to:

   {"style":"a:1, "b":'y', "c":1"}

The b and c are now double quoted and hence throwing errors.
